hyeeyoung/wishboard-android

app/build.gradle
app/src/main/java/com/hyeeyoung/wishboard/MainActivity.kt
app/src/main/java/com/hyeeyoung/wishboard/SplashActivity.kt
app/src/main/java/com/hyeeyoung/wishboard/di/RepositoryModule.kt
app/src/main/java/com/hyeeyoung/wishboard/model/RequestResult.kt
app/src/main/java/com/hyeeyoung/wishboard/model/UserInfo.kt
app/src/main/java/com/hyeeyoung/wishboard/model/WishItem.kt
app/src/main/java/com/hyeeyoung/wishboard/remote/RemoteService.kt
app/src/main/java/com/hyeeyoung/wishboard/repository/home/WishRepository.kt
app/src/main/java/com/hyeeyoung/wishboard/repository/home/WishRepositoryImpl.kt
app/src/main/java/com/hyeeyoung/wishboard/repository/sign/SignRepositoryImpl.kt
app/src/main/java/com/hyeeyoung/wishboard/util/PreferenceUtil.kt
app/src/main/java/com/hyeeyoung/wishboard/util/extension/NavController.kt
app/src/main/java/com/hyeeyoung/wishboard/view/home/HomeFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/view/my/MyFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/view/wish/WishItemListAdapter.kt
app/src/main/java/com/hyeeyoung/wishboard/viewmodel/MyViewModel.kt
app/src/main/java/com/hyeeyoung/wishboard/viewmodel/SignViewModel.kt
app/src/main/java/com/hyeeyoung/wishboard/viewmodel/WishViewModel.kt
app/src/main/res/drawable/background_sticker_white.xml
app/src/main/res/layout/fragment_home.xml
app/src/main/res/layout/fragment_my.xml
app/src/main/res/layout/item_wish.xml
app/src/main/res/navigation/nav_graph.xml
app/src/main/res/navigation/wish_item_nav_graph.xml
app/src/main/res/values/strings.xml

- 프로필에서 닉네임이 없는 경우 유저의 이메일을 hashcode()를 사용하여 6자리 숫자로 변환 후 #199208 과 같은 포맷으로 임시 닉네임이 보이도록 함
- 프로필에서 로그인 및 회원가입 시 인증한 이메일을 띄움

[mod] 프로필에서 닉네임 없는 경우 ui 처리 및 이메일 보여주기

---

app/build.gradle
app/src/main/java/com/hyeeyoung/wishboard/MainActivity.kt
app/src/main/java/com/hyeeyoung/wishboard/SplashActivity.kt
app/src/main/java/com/hyeeyoung/wishboard/di/RepositoryModule.kt
app/src/main/java/com/hyeeyoung/wishboard/model/RequestResult.kt
app/src/main/java/com/hyeeyoung/wishboard/model/UserInfo.kt
app/src/main/java/com/hyeeyoung/wishboard/model/WishItem.kt
app/src/main/java/com/hyeeyoung/wishboard/remote/RemoteService.kt
app/src/main/java/com/hyeeyoung/wishboard/repository/home/WishRepository.kt
app/src/main/java/com/hyeeyoung/wishboard/repository/home/WishRepositoryImpl.kt
app/src/main/java/com/hyeeyoung/wishboard/repository/sign/SignRepositoryImpl.kt
app/src/main/java/com/hyeeyoung/wishboard/util/PreferenceUtil.kt
app/src/main/java/com/hyeeyoung/wishboard/util/extension/NavController.kt
app/src/main/java/com/hyeeyoung/wishboard/view/home/HomeFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/view/wish/WishItemListAdapter.kt
app/src/main/java/com/hyeeyoung/wishboard/viewmodel/SignViewModel.kt
app/src/main/java/com/hyeeyoung/wishboard/viewmodel/WishViewModel.kt
app/src/main/res/drawable/background_sticker_white.xml
app/src/main/res/layout/fragment_home.xml
app/src/main/res/layout/item_wish.xml
app/src/main/res/navigation/nav_graph.xml
app/src/main/res/navigation/wish_item_nav_graph.xml

[feat] 홈화면 아이템 가져오기 구현

---

app/build.gradle
app/src/main/java/com/hyeeyoung/wishboard/MainActivity.kt
app/src/main/java/com/hyeeyoung/wishboard/SplashActivity.kt
app/src/main/java/com/hyeeyoung/wishboard/di/RepositoryModule.kt
app/src/main/java/com/hyeeyoung/wishboard/model/RequestResult.kt
app/src/main/java/com/hyeeyoung/wishboard/model/UserInfo.kt
app/src/main/java/com/hyeeyoung/wishboard/model/WishItem.kt
app/src/main/java/com/hyeeyoung/wishboard/model/WishItemInfo.kt
app/src/main/java/com/hyeeyoung/wishboard/remote/RemoteService.kt
app/src/main/java/com/hyeeyoung/wishboard/repository/home/WishRepository.kt
app/src/main/java/com/hyeeyoung/wishboard/repository/home/WishRepositoryImpl.kt
app/src/main/java/com/hyeeyoung/wishboard/repository/sign/SignRepositoryImpl.kt
app/src/main/java/com/hyeeyoung/wishboard/util/PreferenceUtil.kt
app/src/main/java/com/hyeeyoung/wishboard/util/extension/NavController.kt
app/src/main/java/com/hyeeyoung/wishboard/view/home/HomeFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/view/home/wishitem/WishItemDetailFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/view/wish/WishItemListAdapter.kt
app/src/main/java/com/hyeeyoung/wishboard/viewmodel/SignViewModel.kt
app/src/main/java/com/hyeeyoung/wishboard/viewmodel/WishViewModel.kt
app/src/main/res/drawable/background_sticker_white.xml
app/src/main/res/layout/fragment_home.xml
app/src/main/res/layout/fragment_wish_item_detail.xml
app/src/main/res/layout/item_wish.xml
app/src/main/res/navigation/nav_graph.xml
app/src/main/res/navigation/wish_item_nav_graph.xml

[feat] 아이템 상세조회 구현

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/hyeeyoung/wishboard/SplashActivity.kt
app/src/main/java/com/hyeeyoung/wishboard/view/cart/screens/CartFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/view/folder/screens/FolderFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/view/my/screens/MyFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/view/noti/screens/NotiFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/view/sign/screens/SignActivity.kt
app/src/main/java/com/hyeeyoung/wishboard/view/sign/screens/SignInFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/view/sign/screens/SignUpEmailFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/view/sign/screens/SignUpPasswordFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/view/wish/item/screens/WishBottomSheetDialog.kt
app/src/main/java/com/hyeeyoung/wishboard/view/wish/item/screens/WishFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/view/wish/item/screens/WishItemDetailFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/view/wish/list/adapters/WishItemListAdapter.kt
app/src/main/java/com/hyeeyoung/wishboard/view/wish/list/screens/HomeFragment.kt
app/src/main/res/layout/activity_sign.xml
app/src/main/res/layout/fragment_cart.xml
app/src/main/res/layout/fragment_folder.xml
app/src/main/res/layout/fragment_home.xml
app/src/main/res/layout/fragment_my.xml
app/src/main/res/layout/fragment_noti.xml
app/src/main/res/layout/fragment_sign_in.xml
app/src/main/res/layout/fragment_sign_up_email.xml
app/src/main/res/layout/fragment_sign_up_password.xml
app/src/main/res/layout/fragment_wish.xml
app/src/main/res/layout/fragment_wish_item_detail.xml
app/src/main/res/navigation/nav_graph.xml
app/src/main/res/navigation/sign_nav_graph.xml
app/src/main/res/navigation/wish_item_nav_graph.xml

- view > wish > item, list로 나눔
- home 패키지 삭제 -> wish > list로 이동
- view > 0개 이상 패키지 존재 > screens, adapters 구조로 변경

[mod] 패키지 구조 정리

---

app/src/main/java/com/hyeeyoung/wishboard/di/RepositoryModule.kt
app/src/main/java/com/hyeeyoung/wishboard/model/cart/CartItem.kt
app/src/main/java/com/hyeeyoung/wishboard/model/sign/SignInfo.kt
app/src/main/java/com/hyeeyoung/wishboard/model/sign/UserInfo.kt
app/src/main/java/com/hyeeyoung/wishboard/model/wish/WishItem.kt
app/src/main/java/com/hyeeyoung/wishboard/model/wish/WishItemInfo.kt
app/src/main/java/com/hyeeyoung/wishboard/remote/RemoteService.kt
app/src/main/java/com/hyeeyoung/wishboard/repository/cart/CartRepository.kt
app/src/main/java/com/hyeeyoung/wishboard/repository/cart/CartRepositoryImpl.kt
app/src/main/java/com/hyeeyoung/wishboard/repository/home/WishRepository.kt
app/src/main/java/com/hyeeyoung/wishboard/repository/sign/SignRepositoryImpl.kt
app/src/main/java/com/hyeeyoung/wishboard/repository/wish/WishRepository.kt
app/src/main/java/com/hyeeyoung/wishboard/repository/wish/WishRepositoryImpl.kt
app/src/main/java/com/hyeeyoung/wishboard/view/cart/adapters/CartItemListAdapter.kt
app/src/main/java/com/hyeeyoung/wishboard/view/wish/item/screens/WishItemDetailFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/view/wish/list/adapters/WishItemListAdapter.kt
app/src/main/java/com/hyeeyoung/wishboard/view/wish/list/screens/HomeFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/viewmodel/CartViewModel.kt
app/src/main/java/com/hyeeyoung/wishboard/viewmodel/MyViewModel.kt
app/src/main/java/com/hyeeyoung/wishboard/viewmodel/WishViewModel.kt
app/src/main/res/layout/item_cart.xml
app/src/main/res/layout/item_wish.xml

- 함수명에서 items -> wishList, item -> wishItem 으로 변경
- 패키지 정리
- model > wish, sign, cart 패키지 추가
- repository > home -> wish 로 변경

[chore] 함수명 변경 및 패키지 정리

---

app/src/main/java/com/hyeeyoung/wishboard/view/wish/list/screens/HomeFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/viewmodel/WishViewModel.kt

홈화면에서 위에서 아래로 스와이프할 경우 아이템 목록이 새로고침 되도록 구현

[feat] 홈화면 새로고침 구현

---

app/src/main/java/com/hyeeyoung/wishboard/model/folder/FolderItem.kt
app/src/main/java/com/hyeeyoung/wishboard/model/sign/UserInfo.kt
app/src/main/java/com/hyeeyoung/wishboard/model/wish/WishItem.kt

1. FolderItem > itemCount > String -> Int
2. UserInfo > userId 프로퍼티 삭제 (해당 데이터 클래스는 현재 사용되지 않음)
3. WishItem > cartId > String -> Int? 로 변경

[mod] 데이터 타입 수정

---

app/src/main/java/com/hyeeyoung/wishboard/model/wish/WishItemRegistrationInfo.kt
app/src/main/java/com/hyeeyoung/wishboard/view/wish/item/screens/WishFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/viewmodel/WishItemViewModel.kt
app/src/main/res/layout/fragment_wish.xml

- url 프로퍼티 데이터 타입을 String -> String? 으로 변경
- 아이템 업로드 시 사이트 정보가 존재하지 않아도 등록되도록 하기 위함
- 갤러리 이미지 가져오기를 제외한 아이템 등록 기능 구현 3/4 완료
- 남은 부분
1. 갤러리 이미지 작업은 금요일 내 pr 보낼 예정   
2. 이미지 없이도 등록 가능하도록 수정 필요
3. 가격 데이터가 숫자로만 이루어진 문자열이 아닌 경우 예외 처리 필요
4. 네트워크 연결되지 않은 경우 다이얼로그 띄우기

[feat] 아이템 기본 등록 구현

---

app/src/main/java/com/hyeeyoung/wishboard/model/cart/CartItem.kt
app/src/main/java/com/hyeeyoung/wishboard/model/wish/WishItem.kt
app/src/main/java/com/hyeeyoung/wishboard/model/wish/WishItemInfo.kt
app/src/main/java/com/hyeeyoung/wishboard/remote/RemoteService.kt
app/src/main/java/com/hyeeyoung/wishboard/repository/cart/CartRepository.kt
app/src/main/java/com/hyeeyoung/wishboard/repository/cart/CartRepositoryImpl.kt
app/src/main/java/com/hyeeyoung/wishboard/repository/wish/WishRepository.kt
app/src/main/java/com/hyeeyoung/wishboard/repository/wish/WishRepositoryImpl.kt
app/src/main/java/com/hyeeyoung/wishboard/util/BindingAdapters.kt
app/src/main/java/com/hyeeyoung/wishboard/view/wish/item/screens/WishItemDetailFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/view/wish/list/adapters/WishListAdapter.kt
app/src/main/java/com/hyeeyoung/wishboard/view/wish/list/screens/HomeFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/viewmodel/CartViewModel.kt
app/src/main/java/com/hyeeyoung/wishboard/viewmodel/WishViewModel.kt
app/src/main/res/layout/fragment_wish_item_detail.xml
app/src/main/res/layout/item_cart.xml
app/src/main/res/layout/item_wish.xml

- data class에서 특정 프로퍼티 데이터 타입 변경
- *Id -> Long으로 수정
- count -> Int로 수정
- price -> Int?로 수정 (가격이 null인 경우, 값을 보여줄 때만 0으로 표시하고 있음)
- 화면에서 price 보여줄 때 천 단위 컴마로 구분해서 보여주도록 priceFormat 적용

[mod] 데이터 타입 변경 및 타입 변경에 따른 포맷 적용

---

app/src/main/java/com/hyeeyoung/wishboard/model/cart/CartItem.kt
app/src/main/java/com/hyeeyoung/wishboard/view/cart/adapters/CartListAdapter.kt
app/src/main/java/com/hyeeyoung/wishboard/view/cart/screens/CartFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/viewmodel/CartViewModel.kt
app/src/main/res/layout/item_cart.xml

- 홈조회 및 상세조회 병합에 따른 CartItem data class 수정 및 변경 사항 적용
- `CartListAdapter.kt`, `CartViewModel.kt`, `item_cart.xml` 에서 변경 사항 적용
- 임시 수정한 _CartFragment에서 아이템 클릭 시 DetailFragment로 전환되지 않도록 함_ -> CartItem data class 변경으로 클릭 시 CartItem > wishItem 프로퍼티를 bundle로 전달하도록 처리
- CartFragment.kt에서 cartList 리사이클러뷰의 adapter를 자기 자신으로 초기화하는 코드 오류 수정
- 리사이클러뷰의 adapter와 전역변수로 선언한 adapter의 변수명이 일치하여 어뎁터 초기화 시 CartListAdapter가 아닌 리사이클러뷰의 어뎁터 자신으로 초기화하는 버그를 수정(해당 버그로 cartitem이 보이지 않았던 것임 ^^;;)
```kotlin
binding.cartList.run {
adapter = adapter // -> cartAdapter 로 수정
}
```

[mod] CartItem data class 수정 및 변경사항 적용

---

.github/workflows/android_build.yml

`android_build.yml`
- local.properties 파일 생성 후 해당 파일에 url string값 추가

[add] local.properties 파일 생성

---

app/src/main/java/com/hyeeyoung/wishboard/model/cart/CartItem.kt
app/src/main/java/com/hyeeyoung/wishboard/model/cart/CartItemButtonType.kt
app/src/main/java/com/hyeeyoung/wishboard/remote/RemoteService.kt
app/src/main/java/com/hyeeyoung/wishboard/repository/cart/CartRepository.kt
app/src/main/java/com/hyeeyoung/wishboard/repository/cart/CartRepositoryImpl.kt
app/src/main/java/com/hyeeyoung/wishboard/view/cart/adapters/CartListAdapter.kt
app/src/main/java/com/hyeeyoung/wishboard/view/cart/screens/CartFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/viewmodel/CartViewModel.kt
app/src/main/res/layout/fragment_cart.xml

장바구니 조회, 추가, 삭제 기능은 정상적으로 동작하는 것을 확인했습니다.
**구현해야 할 것**
1. 장바구니 수정부분 서버 코드 연결
2. 장바구니 내 아이템 버튼 클릭 시 수량이 바뀌는 것
3. 장바구니 내 총 개수와 금액 바뀌는 것
2, 3번 구현 중에 PR 먼저 올립니다.

[feat] 장바구니 조회, 추가, 삭제 기능 구현

---

app/src/main/java/com/hyeeyoung/wishboard/remote/RemoteService.kt

아이템 삭제 요청 url 변경
1. 인자 item_id의 어노테이션을 @Field -> @Path로 변경

[chore] 아이템 삭제 요청 url 변경

---

app/src/main/java/com/hyeeyoung/wishboard/remote/RemoteService.kt

[chore] 장바구니 삭제 및 업데이트 요청 url 변경

---

app/src/main/java/com/hyeeyoung/wishboard/repository/folder/FolderRepository.kt
app/src/main/java/com/hyeeyoung/wishboard/repository/folder/FolderRepositoryImpl.kt
app/src/main/java/com/hyeeyoung/wishboard/viewmodel/FolderViewModel.kt
app/src/main/res/layout/dialog_new_folder_add.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/strings.xml

폴더 추가 및 폴더명 수정 시 동일 폴더명이 존재할 경우, "같은 이름의 폴더가 있어요!" 보여주기
1. `createNewFolder()` 및 `updateFolderName()` 반환값에 서버에서 보낸 response.code() 포함
- code == 409에 따라 `viewmodel.isExistFolderName.value`를 true, false로 설정하고, true인 경우 detail 메세지를 보여줌

[feat] 동일 폴더명 검증 프로세스 구현 및 동일 폴더명 존재할 경우 detail 메세지 보여주기

---

app/src/main/res/values/strings.xml

폴더 삭제 description 문구를 수정
1. `해당 폴더에 담긴 모든 아이템이 사라질 수 있어요!` -> `폴더가 삭제되어도 아이템은 사라지지 않아요!`
서버측에서 폴더 삭제 시 해당 아이템들은 삭제되지 않고 folder_id=null로 설정하도록 처리한 것을 반영한 문구입니다!

[mod] 폴더 삭제 description 문구 수정

---

app/src/main/java/com/hyeeyoung/wishboard/view/folder/adapters/FolderListAdapter.kt
app/src/main/java/com/hyeeyoung/wishboard/view/folder/screens/FolderDetailFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/view/folder/screens/FolderFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/view/folder/screens/FolderListFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/view/noti/adapters/NotiListAdapter.kt
app/src/main/java/com/hyeeyoung/wishboard/view/noti/screens/NotiFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/view/wish/list/adapters/WishListAdapter.kt
app/src/main/java/com/hyeeyoung/wishboard/view/wish/list/screens/HomeFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/viewmodel/CartViewModel.kt
app/src/main/java/com/hyeeyoung/wishboard/viewmodel/FolderViewModel.kt
app/src/main/java/com/hyeeyoung/wishboard/viewmodel/NotiViewModel.kt
app/src/main/java/com/hyeeyoung/wishboard/viewmodel/WishListViewModel.kt
app/src/main/res/layout/fragment_cart.xml
app/src/main/res/layout/fragment_folder.xml
app/src/main/res/layout/fragment_folder_detail.xml
app/src/main/res/layout/fragment_folder_list.xml
app/src/main/res/layout/fragment_home.xml
app/src/main/res/layout/fragment_noti.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml

홈, 폴더, 알림, 장바구니에서 알림이 존재하지 않는 경우 "~아이템이 없어요!"와 같은 안내 문구 띄우기
1. 아이템이 존재하지 않을 경우 보여줄 `TextView`추가
<br>
2. 아이템 fetch, 추가 및 삭제 시 `LiveData` 타입의 `wishList, folderList, cartLists, notiList`를 업데이트하고, 각 list의 `size()`에 따라 visibility를 조절
```xml
android:visibility="@{viewModel.folderList.size() > 0 ? View.GONE : View.VISIBLE}"
```
- 홈탭, 폴더탭, 알림탭, 장바구니, 폴더 디테일, 폴더리스트에서 아이템이 존재하지 않을 경우 문구를 확인하실 수 있습니다!

[feat] 아이템이 존재하지 않는 경우 "~아이템이 없어요!" 문구 띄우기

---

app/src/main/java/com/hyeeyoung/wishboard/view/cart/screens/CartFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/view/folder/adapters/FolderListAdapter.kt
app/src/main/java/com/hyeeyoung/wishboard/view/folder/screens/FolderDetailFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/view/folder/screens/FolderFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/view/folder/screens/FolderListFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/view/noti/adapters/NotiListAdapter.kt
app/src/main/java/com/hyeeyoung/wishboard/view/noti/screens/NotiFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/view/wish/list/adapters/WishListAdapter.kt
app/src/main/java/com/hyeeyoung/wishboard/view/wish/list/screens/HomeFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/viewmodel/CartViewModel.kt
app/src/main/java/com/hyeeyoung/wishboard/viewmodel/FolderViewModel.kt
app/src/main/java/com/hyeeyoung/wishboard/viewmodel/NotiViewModel.kt
app/src/main/java/com/hyeeyoung/wishboard/viewmodel/WishListViewModel.kt
app/src/main/res/layout/fragment_cart.xml
app/src/main/res/layout/fragment_folder.xml
app/src/main/res/layout/fragment_folder_detail.xml
app/src/main/res/layout/fragment_folder_list.xml
app/src/main/res/layout/fragment_home.xml
app/src/main/res/layout/fragment_noti.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml

아이템 일반 등록 및 아이템 삭제 후 홈 탭 전환을 반복할 경우 동일 아이템이 추가되거나 아이템이 사라지는 버그를 수정
1. 아이템 추가 및 삭제 등 변경사항이 생긴 아이템의 정보를 bundle 전달 받은 후 bundle.clear()
- bundle을 clear()하면서 아이텐 추가 및 삭제 처리 코드가 중복 실행되는 것을 방지
- 이 커밋만 확인 부탁드립니다! -> 4ea8a19f349b8bf1f8ecd4a46b72969b51964a12

[fix] 아이템 일반 등록 및 아이템 삭제 후 홈 탭 전환을 반복할 경우 동일 아이템이 추가되거나 아이템이 사라지는 버그를 수정

---

app/src/main/java/com/hyeeyoung/wishboard/view/folder/screens/FolderFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/viewmodel/FolderViewModel.kt
app/src/main/res/layout/fragment_folder.xml

폴더 새로고침 추가
1. 폴더 새로고침 뷰 추가
2. 폴더 첫 진입 시(viewModel > init {}) fetchFolderList 실행
- 새로고침 도입했기 때문

[add] 폴더 새로고침 추가

---

app/src/main/java/com/hyeeyoung/wishboard/view/MainActivity.kt
app/src/main/java/com/hyeeyoung/wishboard/view/sign/screens/SignActivity.kt
app/src/main/java/com/hyeeyoung/wishboard/view/wish/item/screens/WishLinkSharingActivity.kt
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/activity_sign.xml
app/src/main/res/layout/activity_wish_link_sharing.xml
app/src/main/res/values/strings.xml

네트워크 연결 해제 토스트 띄우기 -> TextView 보여주기로 변경
1. 네트워크 연결 해제 시 토스트 띄우는 코드 삭제 및 네트워크 연결 확인 TextView 추가
2. 네트워크 연결 상태에 따라 네트워크 연결 확인 TextView의 visibility를 조절 💡
- 오늘 회의에서 논의한 사항입니다. 네트워크 연결 해제된 경우 토스트가 잠시 뜨고 사라졌는데 해제 상태인 경우 네트워크 연결 확인 TextView가 계속 보이도록 수정했습니다. 🥳🥳🥳

[mod] 네트워크 연결 해제 토스트 띄우기 -> TextView 보여주기로 변경

---

app/src/main/java/com/hyeeyoung/wishboard/repository/noti/NotiRepository.kt
app/src/main/java/com/hyeeyoung/wishboard/repository/noti/NotiRepositoryImpl.kt
app/src/main/java/com/hyeeyoung/wishboard/service/RemoteService.kt
app/src/main/java/com/hyeeyoung/wishboard/view/my/screens/MyFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/viewmodel/MyViewModel.kt

서버측 변경사항을 반영해서 pushState 업데이트 요청 api uri를 수정하고 관련 함수의 함수명을 변경
1. pushState 업데이트 요청 api uri 변경
- `@GET("noti/schedule")` -> `@PUT("user/push-state/{push}")`
2. pushState 업데이트 요청 관련함수의 함수명을 수정
- `updatePushNotiSettings()` -> `updatePushState()`

[chore] pushState 업데이트 요청 api uri 수정

---

app/src/main/java/com/hyeeyoung/wishboard/presentation/common/screens/WebViewActivity.kt
app/src/main/java/com/hyeeyoung/wishboard/presentation/my/screens/MyFragment.kt
app/src/main/res/layout/activity_webview.xml
app/src/main/res/layout/fragment_my.xml
app/src/main/res/values/strings.xml

노션 링크 웹뷰로 띄우기 및 마이페이지 관련 코드 정리
1. 노션 링크 웹뷰로 띄우기
2. 웹뷰 > 툴바 하단에 구분선 추가
3. 마이페이지 관련 코드 정리
- 버전 정보 하드코딩 -> BuildConfig.VERSION_NAME 사용
- 불필요한 코드 정리 및 코드 정렬 적용

노션 링크 웹뷰로 띄우기 및 마이페이지 관련 코드 정리

---

app/src/main/java/com/hyeeyoung/wishboard/presentation/cart/CartFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/presentation/cart/CartViewModel.kt
app/src/main/java/com/hyeeyoung/wishboard/util/custom/CustomSnackbar.kt
app/src/main/res/values/strings.xml

장바구니에서 아이템 삭제 시 스낵바가 안뜨는 버그 수정
1. 스낵바 띄우는 코드 추가
- 스낵바 띄우는 코드가 사라짐.. 추가 완
2. 스낵바를 하단으로 띄우기 (모든 스낵바 적용)

[fix] 장바구니에서 아이템 삭제 시 스낵바가 안뜨는 버그 수정

---

app/src/main/java/com/hyeeyoung/wishboard/data/services/FireBaseMessagingService.kt

파이어베이스 알림 데이터 수신 시 notification -> data로 전달받기
1. notification -> data로 수정

[mod] 파이어베이스 알림 데이터 수신 시 notification -> data로 전달받기

---

app/src/main/java/com/hyeeyoung/wishboard/presentation/my/screens/MyFragment.kt

오픈소스 라이브러리 링크 변경
1. 오픈소스 라이브러리 링크를 노션으로 변경

[mod] 오픈소스 라이브러리 링크 변경

---

app/build.gradle
app/src/main/java/com/hyeeyoung/wishboard/presentation/home/HomeFragment.kt
app/src/main/res/layout/fragment_home.xml

- closed #436
1. 만족도 조사 이벤트 뷰 제거
- 이벤트 기간 종료 및 당분간 이벤트 없음.
- 추후 이벤트 도입할 경우 server driven ui 도입으로 이벤트 뷰 띄우기 로직 변경될 것임

만족도 조사 이벤트 뷰 제거
