hyeeyoung/wishboard-android

app/build.gradle
app/src/main/java/com/hyeeyoung/wishboard/remote/RemoteService.kt

`build.gradle`
- BuildConfig > BASE_URL 상수 추가
`RemoteService.kt`
- 기존 BASE_URL 상수 삭제 및 추가된 BuildConfig.BASE_URL 상수 사용
- 사용되지 않는 IMAGE_URL 삭제, 추후 S3 이미지 업로드 PR 보낼 때 BuildConfig에 IMAGE_URL 추가 예정
📌 local.properties 파일에 별도로 보내드린 코드 추가 후 빌드해주세요! 빌드했을 때 BuildConfig.java(.gitignore에 지정됨)파일에 BASE_URL 상수가 추가됩니다!
📌 별도로 보내드린 코드에서 변경된 ip 주소 적용했습니다!

[mod] BuildConfig에 BASE_URL 상수 추가 및 적용

---

app/src/main/java/com/hyeeyoung/wishboard/model/wish/WishItem.kt
app/src/main/java/com/hyeeyoung/wishboard/view/wish/list/adapters/WishListAdapter.kt
app/src/main/java/com/hyeeyoung/wishboard/view/wish/list/screens/HomeFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/viewmodel/WishViewModel.kt

---
- `WishItem.kt` > `val cartId` -> `var cartId`로 변경
- cartId 속성을 변경할 때 단순히 plus(), minus(), times()등 내장함수를 사용하여 값을 바꿀 수 없고, 전달받은 명확한 값으로 reassignment 해주어야하기 때문에 var로 바꿈
- isAddedCart: Boolean 으로 변경 논의 필요 -> 세부내용은 노션 논의사항에 적어두었고, 백엔드는 혜정이가 수정ing..
- `WishViewModel.kt` > wishList 갱신
- ` wishList = MutableLiveData<List<WishItem>>(arrayListOf())` 에서 `wishList = MutableLiveData<MutableList<WishItem>>(mutableListOf())` 로 변경
- `wishList.value?.set(position, wishItem)`으로 item의 변경사항을 반영하기 위함
- MutableList : 변경가능한 List(Immutable)
- 그럼 ArrayList와의 차이는? 제가 궁금해서 찾아봄. 사용 상 차이는 없다고 함 ▶️ [참고](https://stackoverflow.com/questions/43114367/difference-between-arrayliststring-and-mutablelistofstring-in-kotlin)
- `WishListAdapter.kt` > dataSet 갱신
- `fun onCartBtnClick()` 파라미터 수정 `(itemId: Long, isAdded: …

[fix] 홈 화면의 아이템 리스트에서 장바구니 버튼 활성화 상태가 업데이트되지 않는 버그 수정

---

app/src/main/java/com/hyeeyoung/wishboard/remote/RemoteService.kt
app/src/main/java/com/hyeeyoung/wishboard/repository/wish/WishRepository.kt
app/src/main/java/com/hyeeyoung/wishboard/repository/wish/WishRepositoryImpl.kt
app/src/main/java/com/hyeeyoung/wishboard/view/wish/item/screens/WishItemDetailFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/view/wish/list/adapters/WishListAdapter.kt
app/src/main/java/com/hyeeyoung/wishboard/view/wish/list/screens/HomeFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/viewmodel/WishItemViewModel.kt
app/src/main/java/com/hyeeyoung/wishboard/viewmodel/WishListViewModel.kt
app/src/main/res/layout/fragment_wish_item_detail.xml
app/src/main/res/values/strings.xml

상세조회에서 아이템을 삭제할 경우, 서버로 아이템 삭제를 요청하고, 삭제 성공 시 홈화면 ui를 업데이트
1. 아이템 삭제 요청 api 및 함수 추가
- 현재 서버에서 url 변경 작업 중으로, 변경 완료 후 반영 예정
2. 아이템 삭제 성공 시 ui 업데이트
- 삭제 완료 토스트 띄우기
- 홈화면으로 복귀
- 홈화면 > 뷰모델 및 어뎁터의 wishList 에서 삭제된 아이템을 remove
- 주목할 부분은 아이템 삭제 할 때 상세조회 -> 메인화면으로 전환할 때 데이터를 전달하는 것입니다!(홈화면 ui 업데이트를 위함)
- 전달 데이터 : `삭제된 아이템 정보`, `adapter > dataset > position 정보`
- 이전 화면으로 복귀 시 `NavController.popBackStack()` 를 사용했었는데, 이번 경우는 복귀할 때 데이터도 함께 전달해야했습니다. 그래서 다음과 같이 코드를 작성했습니다.
```kotlin
navController.previousBackStackEntry?.savedStateHandle?.set(ARG_WISH_ITEM_INFO, bundleOf(
ARG_WISH_ITEM to viewModel.getWishItem().value,
ARG_WISH_ITEM_POSITION to position
))
navController.popBackStack()
```
- 부연 설명 : `NavController.getPreviousBackStackEntry()`를 사용하여 이전 화면 `NavBackStackEntry`의 `SavedStateHandle`을 사용해서 전달할 …

[feat] 아이템 삭제 구현

---

app/src/main/java/com/hyeeyoung/wishboard/view/wish/list/screens/HomeFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/viewmodel/WishListViewModel.kt

`HomeFragment.kt`에서 호출했던 `wishListAdapter.setData()`를  `WishListViewModel.kt`로 이동 및 불필요한 wishList 변수를 삭제
1. `WishListViewModel.kt`내 `fetchWishList()`에서 fetch완료 후 `wishListAdapter.setData()`를 호출하도록 수정
- 기존 : `HomeFragment.kt`에서 wishList를 observing하면서 `wishListAdapter.setData()` 호출했음
- 변경 : 뷰모델에서 아이템 fetch, update, delete 시 `wishListAdapter.[set | update | delete]Data(요청 결과 값)`바로 호출하기 때문에 홈에서 wishList를 observe하지 않아도 됨

[refactor] WishListViewModel에서 adapter.setData()호출 및 불필요한 wishList 변수 제거

---

app/src/main/java/com/hyeeyoung/wishboard/remote/RemoteService.kt
app/src/main/java/com/hyeeyoung/wishboard/repository/wish/WishRepository.kt
app/src/main/java/com/hyeeyoung/wishboard/repository/wish/WishRepositoryImpl.kt
app/src/main/java/com/hyeeyoung/wishboard/view/wish/item/screens/WishFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/view/wish/item/screens/WishItemDetailFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/viewmodel/WishItemRegistrationViewModel.kt
app/src/main/res/layout/fragment_wish.xml
app/src/main/res/menu/bottom_nav.xml
app/src/main/res/navigation/wish_item_nav_graph.xml

상세조회에서 아이템 수정 버튼을 눌러 수정을 진행할 경우 아이템 정보가 update 되도록 구현
1. 수동등록 화면에서 타이틀 "새아이템" 삭제 및 뒤로가기 버튼 추가
- 아이템 업로드 및 수정에서 동일한 화면을 사용합니다. 이때 상세조회에서 수정버튼을 눌러 `WishFragment.kt`로 진입할 경우, 다시 상세조회로 돌아갈 수 있도록 뒤로가기 버튼을 추가했습니다.
2. BottomNavigationView에서 수동 등록 메뉴 위치만 center로 변경
- 상품 등록 버튼을 강조하기 위해 상품 등록 버튼을 가운데로 두고, 해당 버튼의 디자인만 포인트를 주려고 함(디자인은 아직 적용 전)
3. wish_item_navigation_graph 코드 정리
4. 아이템 수정 구현
- 아이템 이미지 변경여부에 따라 이미지파일을 업데이트 여부를 결정
- 아이템 이미지 변경여부로 케이스를 나누어 아이템 update 테스트해봄 -> 두 케이스 모두 DB update 성공
- 아이템 수정 여부에 따라 update, upload를 올바르게 요청하고 있는지 검토 부탁합니다
- `wish_item_registration_nav_graph.xml` 에서 삭제된 코드는 해당 파일 내 추가한 `<include app:graph="@navigation/wish_item_registration_nav_graph" />` 에 해당 코드가 포함되어있습니다! `<include>`로 `wish_item_registration_nav_graph`를 재사용하는 것으로 봐주시면 좋을 것 같습니다!
- 참고로 현재 코드 상으로는 상세조회 -> 수정 …

[feat] 아이템 수정 구현

---

app/src/main/java/com/hyeeyoung/wishboard/MainActivity.kt
app/src/main/java/com/hyeeyoung/wishboard/model/wish/WishItem.kt
app/src/main/java/com/hyeeyoung/wishboard/view/wish/item/screens/WishFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/view/wish/item/screens/WishItemDetailFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/viewmodel/WishItemRegistrationViewModel.kt
app/src/main/res/values/strings.xml

아이템 수정 완료 후 상세조회 ui 업데이트 구현
1. 아이템 등록(수정) 화면 진입 시 `BottomNavigationView` 숨김
- 수정 중 하단 메뉴를 실수로 눌러 탭 전환되는 문제를 방지하고 함
- 임시저장 기능을 구현하면 굳이 숨기지 않아도 됨. 임시저장은 배포 이후 도입
2. 상품 등록 및 수정 시 띄울 `토스트 메세지` 추가
3. 아이템 수정 완료 후 수정된 아이템 정보를 `DetailFragment` 로 전달 -> 상세조회 ui 업데이트
4. `WishItem.kt` > `image` 프로퍼티 
- `val` -> `var`로 임시 변경
- 리팩토링 이후 원상복구 예정
- 현재 홈 -> 상세조회 -> 수동등록으로 진입한 경우, 이미지를 변경하지 않았을 때의 `wishItem.image` :
- `"http~" 로 시작하는 이미지 url` -> S3에서 이미지 url을 다운로드 받지 않아도 됨
- 이미지 수정 완료 -> 상세조회 -> 수동등록(재수정)으로 진입한 경우, 이미지는 변경하지 않았을 때의 `wishItem.image` : 
- `이미지 파일명` -> S3에서 파일명으로 이미지 url 다운로드 받아야함
- 두 가지 경우에 따라 이미지 load 전 이미지 url을 다운로드 함
- 리팩토링 이후 후자로 통일 예정 -> 리팩토링 완료! 아침에 일어나서 변수명 고민 좀 하고 PR 올릴게요..

[feat] 아이템 수정 완료 후 상세조회 ui 업데이트 구현

---

app/src/main/java/com/hyeeyoung/wishboard/model/wish/WishItem.kt
app/src/main/java/com/hyeeyoung/wishboard/util/ImageLoader.kt
app/src/main/java/com/hyeeyoung/wishboard/util/Util.kt
app/src/main/java/com/hyeeyoung/wishboard/view/wish/item/screens/WishBasicFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/view/wish/item/screens/WishFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/view/wish/item/screens/WishItemDetailFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/view/wish/list/adapters/WishListAdapter.kt
app/src/main/java/com/hyeeyoung/wishboard/view/wish/list/screens/HomeFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/viewmodel/WishItemRegistrationViewModel.kt
app/src/main/java/com/hyeeyoung/wishboard/viewmodel/WishListViewModel.kt
app/src/main/res/layout/fragment_wish.xml
app/src/main/res/navigation/wish_item_registration_nav_graph.xml

이미지를 S3에서 이미지 다운로드 받은 후 이미지를`load`할 때 `loadImage()` 함수를 적용하여 코드를 깔끔하게 정리함
1. `image` 프로퍼티 원상복구
- `var` -> `val`로 변수선언 
2. `Util.kt` S3에서 다운로드 받은 이미지를 `ImageView`에 `load`하는 함수 `loadImage()` 추가
- 어뎁터에서 해당 함수를 호출하고 싶다면, Fragment의 `lifecycleScope`에서 해당 함수를 호출해야함
- 인터페이스 `ImageLoader`를 추가하여 Fragment에서 해당 인터페이스의 `loadImage()`를 구현한다.
- 구현은 `util.kt`의 `loadImage()` 호출하는 것
3. 함수 `loadImage()`를 적용하여 코드를 정리
4. `WishFragment.kt`에서 `WishBasicFragment.kt`로 파일명 수정

[refactor] loadImage 함수를 적용한 리팩토링

---

app/src/main/java/com/hyeeyoung/wishboard/MainActivity.kt
app/src/main/java/com/hyeeyoung/wishboard/remote/RemoteService.kt
app/src/main/java/com/hyeeyoung/wishboard/repository/folder/FolderRepository.kt
app/src/main/java/com/hyeeyoung/wishboard/repository/folder/FolderRepositoryImpl.kt
app/src/main/java/com/hyeeyoung/wishboard/view/folder/adapters/FolderListAdapter.kt
app/src/main/java/com/hyeeyoung/wishboard/view/folder/screens/FolderFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/view/folder/screens/FolderListFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/view/wish/item/screens/WishBasicFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/viewmodel/FolderViewModel.kt
app/src/main/java/com/hyeeyoung/wishboard/viewmodel/WishItemRegistrationViewModel.kt
app/src/main/res/layout/fragment_folder_list.xml
app/src/main/res/layout/fragment_wish.xml
app/src/main/res/layout/item_folder_horizontal.xml
app/src/main/res/layout/item_folder_square.xml
app/src/main/res/navigation/wish_item_registration_nav_graph.xml

아이템 수동 등록 내에서 폴더 리스트 조회 및 아이템 업로드 시 폴더 정보를 설정하는 기능을 구현
1. `FolderListFragment` 진입 시 하단 네이게이션 뷰 숨김 처리
2. 수동 등록 내 폴더리스트 조회 프로세스 구현
- `fetchFolderList` : 폴더탭 폴더리스트 조회
- ``fetchFolderListSummary` : 수동등록 내 폴더리스트 조회
- 기존 폴더탭 내 폴더리스트 조회 요청 함수와 구분하기 위해 Summary를 붙임 // 실제 요약본을 가져오기도 하기 때문
3. 수동 등록 내 폴더리스트 조회 UI 구현 
- `FolderListFragment` 에서 폴더를 선택할 경우, 바로 이전화면으로 돌아가면서 폴더명이 보이도록 UI를 수정
4. 아이템 업로드 또는 수정 시 폴더 정보까지 저장하도록 구현
- `FolderListFragment` 내 리사이클러 뷰 아이템에서 체크박스를 삭제하는 것이 좋을 것 같음. 다음주 회의 때 논의할 예정
- 3번으로 변경되었기 때문

[feat] 아이템 수동 등록 내 폴더 리스트 조회 구현

---

app/src/main/java/com/hyeeyoung/wishboard/model/folder/FolderItem.kt
app/src/main/java/com/hyeeyoung/wishboard/remote/RemoteService.kt
app/src/main/java/com/hyeeyoung/wishboard/repository/folder/FolderRepository.kt
app/src/main/java/com/hyeeyoung/wishboard/repository/folder/FolderRepositoryImpl.kt
app/src/main/java/com/hyeeyoung/wishboard/view/folder/adapters/FolderListAdapter.kt
app/src/main/java/com/hyeeyoung/wishboard/view/folder/screens/FolderAddDialogFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/view/folder/screens/FolderMoreDialogFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/viewmodel/FolderViewModel.kt
app/src/main/res/layout/dialog_new_folder_add.xml
app/src/main/res/navigation/nav_graph.xml
app/src/main/res/values/strings.xml

폴더명 수정 프로세스 및 UI 변경
1. 폴더명 수정 프로세스 구현
- 폴더명 수정 요청 `updateFolderName()`함수 추가
2. 폴더명 수정 UI 변경
- 기존 `FolderAddDialogFragment`와 동일한 UI를 사용하기 때문에 `EditMode`에 따라 update, add 요청(기존 아이템 수동등록과 비슷한 맥락)
- 변경된 폴더명을 적용해서 UI를 업데이트하기 위해 `ForderItem`의 `name`프로퍼티를 `val -> var`로 변수선언 수정
- `FolderAddDialogFragment.kt` 전반적인 리팩토링이 필요하고, 사용되지 않는 뷰모델 삭제 필요
- 파일명 수정 고려 중입니다!

[feat] 폴더명 수정 구현

---

app/src/main/java/com/hyeeyoung/wishboard/view/cart/adapters/CartListAdapter.kt
app/src/main/java/com/hyeeyoung/wishboard/view/cart/screens/CartFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/viewmodel/CartViewModel.kt

장바구니화면에서 totalPrice가 변경되지 않는 버그 수정
1. `totalPrice = MutableLiveData<Int>()` ->  `totalPrice = MediatorLiveData<Int>()`로 변경
- `totalPrice.addSource(cartList) { ... }` : **cartList**를 관찰하여 변경될 때 마다 **totalPrice** 를 계산
- 기존 코드 상에서는 **cartList**가 변경될 때마다 **calculateTotalPrice()** 을 직접 호출해서 가격이 갱신되도록 처리했었는데 아이템 fetch 성공 후 **calculateTotalPrice()** 를 호출하지 않아 가격이 갱신되지 않았던 것이었음
2. **CartItem** 삭제 성공 후 **CartAdapter.dataset**에서 해당 아이템 삭제하도록 변경
- 기존에 삭제 성공 여부 상관 없이 **dataset**에서 바로 제거
- **MediatorLiveData**를 사용하면 하나의 **LiveData**가 하나 이상을 관찰하게 할 수 있습니다.

[fix] 장바구니화면에서 totalPrice가 변경되지 않는 버그 수정

---

app/src/main/java/com/hyeeyoung/wishboard/model/RequestResultId.kt
app/src/main/java/com/hyeeyoung/wishboard/model/RequestResultToken.kt
app/src/main/java/com/hyeeyoung/wishboard/remote/RemoteService.kt
app/src/main/java/com/hyeeyoung/wishboard/repository/folder/FolderRepository.kt
app/src/main/java/com/hyeeyoung/wishboard/repository/folder/FolderRepositoryImpl.kt
app/src/main/java/com/hyeeyoung/wishboard/repository/sign/SignRepositoryImpl.kt
app/src/main/java/com/hyeeyoung/wishboard/view/folder/adapters/FolderListAdapter.kt
app/src/main/java/com/hyeeyoung/wishboard/viewmodel/FolderAddDialogViewModel.kt
app/src/main/java/com/hyeeyoung/wishboard/viewmodel/FolderViewModel.kt

폴더 추가 시 서버에서 결과값으로 id값을 보내주는 것으로 수정함에 따라 `RequestResult`관련 dataClass를 수정했고, id값을 받아서 폴더 추가 시 UI가 업데이트 되도록 구현
1. `RequestResultId` 데이터 클래스 추가 및 `RequestResultToken`에서 `@SerializedName("data")` 추가
- 원래 `RequestResultId`와 `RequestResultToken`을 하나의 클래스로 사용하고 싶었으나 data의 데이터 타입이 다음과 같이 구분되어 합칠 수 없었음
-  token값을 전달 받을 경우 : **String**
- id값을 전달 받을 경우 : **Long**
2. 폴더 추가 시 전달 받은 폴더 id값 + 폴더명으로 `FolderItem`을 생성해서 `adapter.dataset`에 추가하여 UI를 업데이트
- 폴더 추가 후 해당 폴더 폴더명 수정도 가능
- 서버에서는 RequestResult로 data를 지금과 같이 보내줘도 괜찮을 것 같습니다! 안드에서 data를 사용맥락에 맞춰서 `@SerializedName("..")`을 사용하여 프로퍼티명을 바꾸겠습니다!!

[feat] 폴더 추가 시 ui 업데이트 구현

---

app/src/main/java/com/hyeeyoung/wishboard/viewmodel/FolderViewModel.kt

폴더 추가 후 또 다른 폴더 추가 시 새폴더가 생성되지 않는 버그를 수정
1. FolderViewModel.kt에서 isEditMode의 초깃값을 null -> false로 설정
- 원인 : 폴더 수정을 한번도 하지 않았을 때, 폴더 추가 후 또 다른 폴더 추가할 경우 isEditMode 가 null 값이면 `viewModel.createNewFolder()`이 호출되지 않아 새폴더가 생성되지 않았던 것임
```kotlin
// FolderAddDialogFragment.kt
binding.add.setOnClickListener {
when (viewModel.getEditMode().value) {
true -> viewModel.updateFolderName(folderItem, position)
false -> viewModel.createNewFolder() // false일 때만 실행
}
}
```

[fix] 폴더 추가 후 또 다른 폴더를 추가할 경우 폴더가 추가되지 않는 버그 수정

---

app/src/main/java/com/hyeeyoung/wishboard/view/folder/screens/FolderAddDialogFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/viewmodel/FolderViewModel.kt

폴더 추가 및 폴더명 수정을 구분하는 `isEditMode` 설정 관련 코드 리팩토링함
1. `FolderAddDialogFragment.kt`에서 arguments 존재 여부에 따라 `isEditMode` 를 설정
2. `FolderAddDialogFragment.kt` 진입 즉, 다이얼로그 띄울 때 폴더 업로드 관련 데이터를 reset하는 `resetFolderData()` 호출

[refactor] 폴더 추가 및 폴더명 수정을 구분하는 isEditMode 설정 관련 코드 리팩토링

---

app/src/main/java/com/hyeeyoung/wishboard/view/wish/item/screens/WishBasicFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/viewmodel/WishItemRegistrationViewModel.kt
app/src/main/res/layout/activity_wish_link_sharing.xml
app/src/main/res/layout/fragment_cart.xml
app/src/main/res/layout/fragment_wish.xml

아이템 업로드 및 장바구니화면에서 가격 포맷 적용
1. 아이템 등록 및 수정 시 가격 EditText에 천단위 구분자를 적용
- EditText 이기 때문에 xml에서 바로 priceFormat 적용 어려움, viewModel에서 처리
2. 장바구니 하단 totalPrice에 TextView에 천단위 구분자를 적용
- DB에는 구분자 없이 number 타입 그대로 저장됩니다
- view : 130,000
- db : 130000 
- `android:selection="@{viewModel.itemPrice.length()}"`: price EditText에서 가격 변경 시 마다 커서가 제일 앞으로 이동하기 때문에 맨뒤로 옮겨야함. -> 커서가 앞에 있으면 가격이 30,000원 일때 1을 입력할 경우, 130,000 이 되버림
- text, selection 순을 유지해야함 그렇지 않을 경우, `IndexOutOfBoundsException: setSpan ~~ ends beyond length ~` 에러 발생
- 실행 순서에 따른 에러로 파악 : text 가 먼저 지정된 후 해당 text의 length를 받아와야 IndexOutOfBoundsException 을 방지할 수 있음
- 해당 부분을 해결하기위해 많은 시간 소모됨 🥲
- 코드 리포맷 적용 시 text와 selection 순서 뒤바뀜 주의
- xml에서 일부 TextSize 속성값을 dp -> sp로 변경 필요합니다. 이슈 추가후 작업 예정
- ci 실패는 해당 PR과는 관련 없음
-  알림 관련 환경변수 키를 찾지 못해 발생하는 에러로 머지되면 …

아이템 업로드 및 장바구니화면에서 가격 포맷 적용

---

app/src/main/res/layout/activity_splash.xml
app/src/main/res/layout/fragment_my.xml
app/src/main/res/layout/fragment_sign_in.xml
app/src/main/res/layout/fragment_sign_up_email.xml
app/src/main/res/layout/fragment_sign_up_password.xml
app/src/main/res/layout/item_cart.xml
app/src/main/res/layout/item_folder_horizontal.xml
app/src/main/res/layout/item_folder_square.xml
app/src/main/res/layout/item_noti.xml
app/src/main/res/layout/item_wish.xml

backgound 컬러가 지정되지 않은 화면의 배경색을 white로 적용 
- item_*.xml의 경우 기존 배경색을 제거함
- fragment의 배경색이 white이기 때문에 추가로 배경색을 지정할 필요없음

[mod] background 컬러 white로 적용

---

app/src/main/java/com/hyeeyoung/wishboard/view/folder/screens/FolderAddDialogFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/view/folder/screens/FolderDeleteDialogFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/view/folder/screens/FolderFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/view/folder/screens/FolderListFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/view/folder/screens/FolderMoreDialogFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/view/wish/item/screens/WishBasicFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/viewmodel/FolderViewModel.kt
app/src/main/java/com/hyeeyoung/wishboard/viewmodel/WishItemRegistrationViewModel.kt
app/src/main/res/layout/dialog_new_folder_add.xml
app/src/main/res/layout/fragment_folder_list.xml
app/src/main/res/navigation/nav_graph.xml

아이템 업로드 시 폴더가 한번에 지정되지 않는 버그와 폴더 더보기에서 폴더명 수정 및 폴더 삭제 다이얼로그로 전환되지 않는 버그를 수정
1. 폴더가 한번에 지정되지 않는 버그 수정
- 원인 : 폴더 지정 후 아이템 업로드 화면으로 복귀 시 `bundle`로 폴더 정보를 전달하는 과정에서 처음 폴더를 지정할 경우 null이 전달되었음
- 해결 : 폴더 정보를 `bundle`로 전달하지 않고, `WishItemRegistrationViewModel.kt`에 바로 폴더 정보를 저장하는 방식으로 변경
- `FolderViewModel.kt`에서 `fetchFolderListSummary()`를 `WishItemRegistrationViewModel.kt`로 옮기고 함수명을 `fetchFolderList()`로 변경
2. 폴더 더보기에서 폴더명 수정 및 폴더 삭제 다이얼로그로 전환되지 않는 버그 수정 
- gradle 및 각종 라이브러리 버전을 업그레이드 하면서 해당 버그가 발생
- 폴더 더보기 다이얼로그에서 dismiss 후 폴더명 수정 및 폴더 삭제 다이얼로그로 이동했을 때 해당 다이얼로그도 바로 dismiss 되었던 것이 원인
- 전환 시 navigation을 사용하지 않고 dialog.show()를 명시적으로 호출하여 `FolderAddDialogFramgent.kt`와 `FolderDeleteDialogFramgent.kt`로 전환하도록 수정
- 폴더 추가 및 삭제 다이얼로그가 잘 뜨는지 확인 부탁합니다!
- 아이템 등록 시 폴더가 잘 지정되는지도 확인 부탁해요!
- gradle 버전과 라이브러리 버전을 …

[fix] 폴더 지정 버그 및 폴더 수정 및 삭제 다이얼로그 전환 버그 수정

---

app/src/main/java/com/hyeeyoung/wishboard/view/cart/adapters/CartListAdapter.kt
app/src/main/java/com/hyeeyoung/wishboard/view/cart/screens/CartFragment.kt
app/src/main/res/layout/fragment_cart.xml

장바구니화면에서 아이템 수량 변경 시 하단의 구분선이 깜박이는 버그 및 recyclerView 스크롤 시 전체적으로 아이템 이미지가 깜박이는 버그를 수정
1. 구분선 깜박이는 버그 수정
- 원인 : 수량 변경 시 실행되는 > `CartListAdapter.kt` > `updateItem()` > `notifyItemChanged(position)` 실행 시 뷰에 에니메이션 효과가 적용되어 발생하는 버그
- 해결 : 에니메이션 제거를 위해 recyclerview > `itemAnimator = null` 추가
2. recyclerView 스크롤 시 전반적으로 이미지 깜박임 버그 수정
-  `setItemViewCacheSize(20)` : 스크롤 되어 화면에 사라진 view에 대해서는 재사용되는 `recycled view pool`에 들어가지 않고, `cache`에 저장(사이즈는 20). 다시 화면에 view가 등장할 때 `onBindViewHolder` 호출 없이 그대로 보여짐
3. 그 외 `recyclerView` 성능 개선
- 1, 2번 작업도 `recyclerView` 성능 개선에 포함됨
- `diffCallback` 사용 : 두 `itemList`간의 차이점을 찾고 업데이트 되어야 할 list를 반환, 변경된 list에 대한 부분 업데이트 실행
- `CartListAdapter.kt` > `RecyclerView.Adapter` -> `ListAdapter` 상속으로 변경, `diffcallback`을 간편하게 사용하기 위함
- `setHasStableIds(true)`, `getItemId()` : …

[fix] 장바구니 아이템 깜박임 버그 수정

---

app/src/main/java/com/hyeeyoung/wishboard/view/folder/adapters/FolderListAdapter.kt
app/src/main/java/com/hyeeyoung/wishboard/view/folder/screens/FolderFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/view/folder/screens/FolderListFragment.kt
app/src/main/res/layout/fragment_folder.xml
app/src/main/res/layout/fragment_folder_list.xml

폴더 리스트 깜박임 및 무분별한 썸네일 이미지가 로드되는 버그 수정
1. recyclerView 성능 개선
- `diffCallback`  사용
- 어뎁터 `setHasStableIds(true)` 설정
-  리사이클러뷰 `itemAnimator = null`, `setItemViewCacheSize(20)` 설정 -> 무분별한 썸네일 이미지 로드 해결
- 불필요한 새로고침 삭제하여 깜박임이 발생하지 않도록 수정
- `fragment_folder.xml`은 SwipeRefreshLayout만 제거했습니다! 가볍게 봐주세요!

[fix] 폴더 리스트 깜박임 및 무분별한 썸네일 이미지가 로드되는 버그 수정

---

app/src/main/java/com/hyeeyoung/wishboard/view/wish/list/adapters/WishListAdapter.kt
app/src/main/java/com/hyeeyoung/wishboard/view/wish/list/screens/HomeFragment.kt

홈에서 스크롤 시 RecyclerView가 깜박이는 버그 수정
1. recyclerView  > `setItemViewCacheSize(20)`
- 스크롤 되어 화면에 사라진 view는 재사용되는 `recycled view pool`에 들어가지 않고, `cache`에 저장 다시 화면에 view가 등장할 때 `onBindViewHolder` 호출 없이 그대로 보여짐에 따라 깜박임 완화
2. recyclerView 성능 개선
- 1번도 recyclerView 성능 개선에 포함됨
- `WishListAdapter.kt` : `diffCallback` 사용, `setHasStableIds(true)` 설정

[fix] 홈에서 스크롤 시 RecyclerView가 깜박이는 버그 수정

---

app/src/main/java/com/hyeeyoung/wishboard/util/PreferenceUtil.kt
app/src/main/java/com/hyeeyoung/wishboard/view/my/screens/MyFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/viewmodel/MyViewModel.kt
app/src/main/res/layout/fragment_my.xml

`selectUserInfo()` api 요청 시 전달받는 `push_state` 값에 따라 알림 스위치(on/off) ui를 업데이트를 구현
1. 전달받는 `push_state`값에 따라 알림 스위치(on/off) ui가 업데이트 되도록 구현
- ui 업데이트를 위해 `LiveData` 타입의 `pushState` 변수를 추가
- 해당 변수는 유저의 `push_state`값을 불러올 때와 알림 스위치 변경 시 값이 변경됨
- `pushState`값을 `databinding`해서 ui 업데이트 : android:checked="@{viewModel.pushState}"
<br>
2. 스위치 on/off값 변경 감지 리스너를 `setOnCheckedChangeListener` -> `setOnClickListener`로 교체
```
1. 스위치를 변경한 경우 : pushState 업데이트 api 요청 + 스위치 ui업데이트
2. 마이페이지 진입 시 push_state값 fetch : only 스위치 ui 업데이트
```
기존 : `setOnCheckedChangeListener`를 사용하면 2번 경우에도 스위치 ui업데이트를 요청할 수 있음**
변경 : `setOnClickListener`로 교체하면서 데이터 바인딩 상관 없이 switch on/off를 위해 클릭하면 1번과 같이 동작하게 됨
<br>
3. `push_state` 관련 프리퍼런스 함수 삭제
- 마이페이지 스위치 ui를 업데이트하기 위한 함수
- 마이페이지 진입 시 `userInfoFetch`로 `push_state`도 함께 전달해주면서 앱 내 …

[feat] push_state에 따라 마이페이지 알림 스위치 on/off ui를 구현

---

app/src/main/java/com/hyeeyoung/wishboard/service/AWSS3Service.kt
app/src/main/java/com/hyeeyoung/wishboard/viewmodel/WishItemViewModel.kt

아이템이 삭제 완료된 경우 s3 버킷에서도 이미지 객체가 삭제되도록 구현
1. s3에서 이미지 삭제하는 함수 추가
```kotlin
suspend fun removeImageUrl(fileName: String) {
try {
val result = Amplify.Storage.remove(fileName)
Log.d(TAG, "Successfully removed ${result.key}")
} catch (error: StorageException) {
Log.e(TAG, "Remove failure", error)
}
}
```
2. 아이템 삭제 완료된 경우 1번 함수 실행

[feat] 아이템 삭제 완료 후 s3에서 이미지 삭제 구현

---

app/src/main/java/com/hyeeyoung/wishboard/model/cart/CartItem.kt
app/src/main/java/com/hyeeyoung/wishboard/repository/cart/CartRepository.kt
app/src/main/java/com/hyeeyoung/wishboard/repository/cart/CartRepositoryImpl.kt
app/src/main/java/com/hyeeyoung/wishboard/view/cart/adapters/CartListAdapter.kt
app/src/main/java/com/hyeeyoung/wishboard/view/cart/screens/CartFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/view/folder/screens/FolderDetailFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/viewmodel/CartViewModel.kt

아이템 수정 후 ui 업데이트 구현
1. `CartItem.kt` > `wishItem` 프로퍼티 val -> var로 수정
- 상세조회에서 아이템 수정 후 `cartItem.wishItem`이 수정 가능해야하기 때문에 변경
<br>
2. `updateCartInfo -> updateCartItemCount` 로 함수명 수정
- 업데이트 대상(count)을 명확하게 구분하기 위해 함수명을 수정함
```
[CartViewModel.kt]
updateCartItemCount() : 아이템 수량만 업데이트
updateCartItem() : 상세조회에서 아이템 수정 후 cartItem.wishItem만 업데이트, 함수명 후보로 updateWishItem(), updateCartWishItem()도 해봤지만, CartViewModel에 맞게, 변수명 짧게 유지하기 위해 updateCartItem()으로 정함
```
```
[CartViewModel.kt]
// 메서드 오버로딩, 두 함수 모두 notifyItemChanged(position)을 실행해야하므로 함수명을 동일하게 유지
updateCartItem(position: Int, cartItem: CartItem) : 실제로는 cartItem.itemCount만 업데이트, cartItem: CartItem -> count: Int로 리팩토링 예정
updateCartItem(position: Int, wishItem: WishItem) : 실제로는 cartItem.wishItem만 업데이트
```
<br>
3. 아이템 수정 후 장바구니 및 폴더 디테일로 복귀 시 …

[feat] 아이템 수정 후 ui 업데이트 구현

---

app/src/main/java/com/hyeeyoung/wishboard/view/wish/item/screens/WishBasicFragment.kt

아이템 수정화면에서 갤러리 화면 전환 시 이미지를 선택하지 않고 back버튼 눌러 복귀할 경우, 기존 이미지가 사라지는 버그 수정
1. `Glide.with(binding.itemImage).load(viewModel.getWishItem()?.imageUrl).into(binding.itemImage)` 코드 위치를 initializeView()로 변경
- 원인 : 아이템 수정 화면 첫 진입 시만 해당 코드가 실행되고, 그 갤러리화면 갔다오면 해당 코드가 실행되지 않아 이미지가 보이지 않았던 것임
2. arguments 전달 받는 코드를 `onCreate()`로 옮김
```kotlin
arguments?.let {
(it[ARG_IS_EDIT_MODE] as? Boolean)?.let { isEditable ->
isEditMode = isEditable // 아이템 수정으로 화면 진입했는지 구분
}
(it[ARG_WISH_ITEM] as? WishItem)?.let { item ->
viewModel.setWishItem(item) // 수정으로 들어왔을 때 해당 아이템의 정보로 ui 업데이트하기 위해 viewModel에 아이템 정보 저장 
}
}
```
3. 사용되지 않는 `isVisited` 변수 삭제

[fix] 아이템 수정화면에서 갤러리 화면 전환 시 기존 이미지가 사라지는 버그 수정

---

app/src/main/java/com/hyeeyoung/wishboard/view/cart/adapters/CartListAdapter.kt
app/src/main/java/com/hyeeyoung/wishboard/view/folder/adapters/FolderListAdapter.kt
app/src/main/java/com/hyeeyoung/wishboard/view/noti/adapters/NotiListAdapter.kt
app/src/main/java/com/hyeeyoung/wishboard/view/wish/list/adapters/WishListAdapter.kt

새폴더 또는 아이템이 없는 폴더임에도 불구하고 폴더 썸네일이 보이는 버그를 수정
1. `override fun getItemId(position: Int): Long` 반환 값을 아래와 같이 고유한 id값으로 변경
- 해결: `position.toLong()` -> `dataSet[position].wishItem.id ?: 0`
- 설명 : 고유한 id는 뷰 자체에 대한 참조 시 사용함 -> ui 업데이트 / 삭제 작업 수행
- 원인 : 바인딩하는 코드는 문제가 없었으나 고유한 id값이 아니였기 때문에 ui 업데이트가 제대로 이루어지지 않았던 것임
2. 다른 Adapter에서도 버그 발생 방지를 위해 `getItemId(position: Int)`의 반환값을 고유한 id값으로 변경함

[fix] 폴더 썸네일이 잘못 매칭되는 버그 수정

---

app/src/main/java/com/hyeeyoung/wishboard/util/custom/CustomSnackbar.kt
app/src/main/java/com/hyeeyoung/wishboard/view/folder/screens/FolderAddDialogFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/view/folder/screens/FolderFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/view/my/screens/MyFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/view/my/screens/MyProfileEditFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/view/sign/screens/SignInFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/view/wish/item/screens/WishBasicFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/view/wish/item/screens/WishItemDetailFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/view/wish/item/screens/WishLinkSharingActivity.kt
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/activity_wish_link_sharing.xml
app/src/main/res/layout/fragment_folder.xml
app/src/main/res/layout/fragment_my.xml
app/src/main/res/layout/fragment_profile_edit.xml
app/src/main/res/layout/fragment_sign_in.xml
app/src/main/res/layout/fragment_wish_item_detail.xml
app/src/main/res/layout/snackbar_item.xml
app/src/main/res/values/styles.xml

커스텀 스낵바를 구현하고 기존 `Toast -> CustomSnackbar`로 적용
1. `CustomSnackbar.kt`추가
- 커스텀 레이아웃 적용 : `SnackbarItemBinding`
- 스낵바가 뜨는 위치를 조정
- 기존 : 토스트가 중간에 떠서 화면 중앙을 가리는 이슈가 있었음
- 변경 : 커스텀 토스트를 적용하면서 `isTop`이라는 인자로 스낵바가 뜨는 위치를 최상단(default), 최하단으로 적용
- 비고 : 링크 등록, 로그인을 제외한 모든 스낵바는 최상단에 뜸
- 링크 등록 스낵바(상품 등록 완료) : `BottomSheetDialog`로 다이얼로그 동일하게 위치를 bottom으로 설정 
- 로그인 스낵바(로그인 실패) : 상단에 있는 로그인 입력 뷰를 가리지않도록 위치를 bottom으로 설정 
<br>
2. 모든 `Toast -> CustomSnackbar`로 변경
<br>
3. CustomSnackbar 스타일 추가 및 적용
- 적용대상
- `activity_main.xml` > 네트워크 연결상태뷰(실제로는 TextView이지만 Snackbar와 동일한 스타일으로 적용)
- `item_snackbar.xml`
- 스낵바 디자인은 피그마에 업로드 했습니다! 최근 댓글 참고하시면 좋을 것 같습니다!

[feat] 커스텀 스낵바 구현

---

app/src/main/java/com/hyeeyoung/wishboard/view/wish/item/screens/WishBasicFragment.kt
app/src/main/res/layout/fragment_wish.xml

이미지 수정 전용 카메라 아이콘 삭제
1. 아이템 일반 등록에서 갤러리 화면 진입을 위한 카메라 아이콘 2개 중 우측 하단의 카메라 아이콘을 제거
- 기존 : 선택된 이미지가 있는 경우, 센터에 있는 카메라 아이콘은 사라지고, 우측 하단 아이콘이 보였음
- 변경 : 이미지 선택여부 상관 없이 센터에 있는 카메라 아이콘이 항상 보임

[delete] 이미지 수정 전용 카메라 아이콘 삭제

---

app/src/main/java/com/hyeeyoung/wishboard/model/common/DialogButtonReplyType.kt
app/src/main/java/com/hyeeyoung/wishboard/view/folder/screens/FolderAddDialogFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/view/folder/screens/FolderFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/viewmodel/FolderViewModel.kt
app/src/main/res/navigation/nav_graph.xml

폴더 추가 및 폴더명 수정 관련 파일 리팩토링
1. `DialogButtonReplyType.kt` CLOSE(닫기 버튼) 추가
<br>
2. `FolderFragment.kt`> `showFolderUploadDialog()` 추가
- 폴더탭에서 폴더 업로드 다이얼로그로 화면전환 -> 직접 다이얼로그 띄우기
<br>
3. `FolderAddDialogFragment.kt` 정리
- 폴더탭에서 직접 다이얼로그를 띄우면서 다이얼로그에서 처리한 것을 `FolderFragment.kt`에서 처리하게 됨
- 폴더 업로드 처리 코드가 `FolderAddDialogFragment.kt` - > `FolderFragment.kt`로 이동
<br>
4. `nav_graph.xml`에서 폴더 관련 다이얼로그 `action` 삭제
- 화면 전환이 필요없게됨에 따라 삭제(2번 설명 참고)

[refactor] 폴더 업로드 관련 파일 리팩토링

---

app/src/main/java/com/hyeeyoung/wishboard/repository/noti/NotiRepository.kt
app/src/main/java/com/hyeeyoung/wishboard/repository/noti/NotiRepositoryImpl.kt
app/src/main/java/com/hyeeyoung/wishboard/service/RemoteService.kt
app/src/main/java/com/hyeeyoung/wishboard/view/folder/screens/FolderAddDialogFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/view/folder/screens/FolderFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/view/my/screens/MyFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/viewmodel/MyViewModel.kt

폴더 수정 후 폴더탭 전환 반복시 마다 스낵바가 뜨는 버그 수정
1. 다이얼로그가 닫힐 때 마다 `viewModel.resetFolderData()` 호출
- 스낵바는 isCompleteUpload()(폴더 업로드 성공 여부)가 true 인 경우 뜸 -> 폴더 업로드 성공 후, 스낵바가 뜨고, 다이얼로그가 닫힐 때 해당 데이터를 초기화하는 `viewModel.resetFolderData()` 호출
-𖤐## To Reviewers 📢
- 5b15d2730fbf38751f6e0f14d7c296c69d40a403 해당 커밋만 확인해주세요!

[fix] 폴더 수정 후 폴더탭 전환 반복시 마다 스낵바가 뜨는 버그 수정

---

app/src/main/java/com/hyeeyoung/wishboard/util/BindingAdapters.kt
app/src/main/java/com/hyeeyoung/wishboard/util/TimeUtil.kt
app/src/main/res/values/strings.xml

날짜 포맷에 관련해서 버그를 수정 및 포맷추가 및 수정을 작업
1. n년 전 포맷에서 n이 잘못 표기되는 버그를 수정
- 19개월이 1년 전이 아닌 19개월로 표기되는 버그가 있었음
- 원인 : 개월 계산에서 코드 작성하다 끝냄..😅
- 해결 :  n년으로 바꾸기 위해 `difftime(month)`을 `MONTH(12)`로 나누기 추가
2. n주 전 포맷을 추가
3. n달 전 -> n개월 전으로 string 수정

[mod] 날짜 포맷 수정 

---

app/src/main/java/com/hyeeyoung/wishboard/model/wish/WishItem.kt
app/src/main/java/com/hyeeyoung/wishboard/view/MainActivity.kt
app/src/main/java/com/hyeeyoung/wishboard/view/folder/FolderListDialogListener.kt
app/src/main/java/com/hyeeyoung/wishboard/view/folder/adapters/FolderListAdapter.kt
app/src/main/java/com/hyeeyoung/wishboard/view/folder/screens/FolderListBottomDialogFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/view/folder/screens/FolderListFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/view/wish/item/screens/WishBasicFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/view/wish/item/screens/WishItemDetailFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/viewmodel/FolderViewModel.kt
app/src/main/java/com/hyeeyoung/wishboard/viewmodel/WishItemRegistrationViewModel.kt
app/src/main/java/com/hyeeyoung/wishboard/viewmodel/WishItemViewModel.kt
app/src/main/res/drawable/ic_check_circle.xml
app/src/main/res/drawable/ic_close.xml
app/src/main/res/layout/dialog_bottom_folder_list.xml
app/src/main/res/layout/fragment_wish_item_detail.xml
app/src/main/res/layout/item_folder_horizontal.xml
app/src/main/res/navigation/wish_item_registration_nav_graph.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml

아이템 디테일뷰에서 폴더 지정 기능 및 ui 구현
1. 아이템 디테일 뷰에서 폴더 지정 기능 추가
- `WishItemViewModel.kt` > `updateWishItemFolder()`
- 추가폴더 업데이트를 위한 아이템 업데이트 api 요청, 배포 이후 서버에서 api 추가 시 api 변경 예정
-  `WishItem.kt` > `folderName`, `folderId` 프로퍼티 `val -> var`로 변경
- 폴더 업데이트를 위해 해당 프로퍼티에 값 재할당이 가능해야함 
- `FolderListDialogListener.kt` 추가
- 폴더지정 다이얼로그에서 선택한 폴더 정보를 받아오기 위한 인터페이스 
<br>
2. 아이템 디테일뷰, 일반 등록 뷰에서 폴더 지정 다이얼로그 띄우기
- 기존 일반 등록 > 폴더리스트 뷰는 일반 fragment였음. -> 다이얼로그로 통일함
- Navigation graph에서 기존 일반 등록 > 폴더리스트 뷰로 이동하는 action 제거
- 체크 아이콘(선택된 폴더를 체크 표시)과 "X"버튼 두께를 좀 더 두껍게 변경
<br>
3. 디테일뷰 폴더명에 패딩을 주어 터치 가능 영역을 넓힘
- 일반 등록과 링크공유 알림 설정 뷰도 다이얼로그 형식으로 모두 통일 예정입니다! 
- 디테일뷰와 일반 등록에서 폴더 지정 테스트 부탁드립니다!
- 슬랙에서 말씀드린 `FolderListAdapter.kt`(를 포함한 전체 어뎁터)에서 diffUtil 동작 안되는 현상은 `FolderListAdapter.kt`에 주석으로 달았고, 기존 구현 방식을 따르려고 합니다! 배포 이후에 …

[feat] 아이템 디테일뷰에서 폴더 지정 기능 및 ui 구현

---

app/src/main/java/com/hyeeyoung/wishboard/view/folder/screens/FolderUploadBottomDialogFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/view/noti/screens/NotiSettingBottomDialogFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/view/wish/item/screens/WishBasicFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/view/wish/item/screens/WishLinkSharingActivity.kt
app/src/main/res/layout/activity_wish_link_sharing.xml
app/src/main/res/layout/dialog_bottom_folder_list.xml
app/src/main/res/layout/dialog_bottom_folder_upload.xml
app/src/main/res/layout/dialog_bottom_noti_setting.xml
app/src/main/res/navigation/wish_item_registration_nav_graph.xml
app/src/main/res/values/dimens.xml

아이템 등록 관련 폴더 및 알림 설정 다이얼로그 ui 수정
1. 다이얼로그 툴바를 제외한 content 높이를 264dp(고정값)으로 통일
- 적용대상 : `FolderUploadBottomDialogFragment.kt`, `NotiSettingBottomDialogFragment .kt`, `LinkSharingActivity.kt`
- 각 레이아웃에서 id=content의 높이를 264dp로 수정
<br>
2. `FolderUploadBottomDialogFragment.kt`, `NotiSettingBottomDialogFragment .kt` 수정
- `FolderUploadBottomDialogFragment.kt`, `NotiSettingBottomDialogFragment .kt`에서 다이얼로그 사이즈를 지정하는 onStart() 함수 제거
```kotlin
override fun onStart() {
super.onStart()
dialog?.window?.setLayout(
WindowManager.LayoutParams.MATCH_PARENT,
resources.getDimensionPixelSize(R.dimen.widgetBottomDialogHeightBase)
)
dialog?.window?.setBackgroundDrawableResource(android.R.color.transparent)
dialog?.window?.setGravity(Gravity.BOTTOM)
}
```
- `DialogFragment ` -> `BottomSheetDialogFragment()`로 …

아이템 등록 관련 폴더 및 알림 설정 다이얼로그 ui 수정

---

app/src/main/java/com/hyeeyoung/wishboard/data/model/noti/NotiItem.kt
app/src/main/java/com/hyeeyoung/wishboard/data/model/wish/ItemDetail.kt
app/src/main/java/com/hyeeyoung/wishboard/domain/repositories/WishRepository.kt
app/src/main/java/com/hyeeyoung/wishboard/presentation/noti/screens/NotiSettingBottomDialogFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/presentation/noti/types/NotiType.kt
app/src/main/java/com/hyeeyoung/wishboard/presentation/wishitem/viewmodels/WishItemRegistrationViewModel.kt
app/src/main/java/com/hyeeyoung/wishboard/util/NumberPickerUtil.kt
app/src/main/java/com/hyeeyoung/wishboard/util/extension/StringExt.kt
app/src/main/res/layout/activity_wish_link_sharing.xml
app/src/main/res/layout/fragment_wish.xml
app/src/main/res/layout/fragment_wish_item_detail.xml
app/src/main/res/layout/item_calendar_noti.xml
app/src/main/res/layout/item_noti.xml

알림유형 데이터타입을 NotiType -> String으로 변경
알림유형을 enum 클래스에서 정의한 변수명으로 저장 -> 한글 String으로 저장하는 방식으로 변경하게 되었음
1. 서버 통신 시 알림유형을 NotiType -> String으로 받도록 수정
- data 레이어 모델을 domain 레이어 모델로 변환하는 과정에서 다시 String -> NotiType으로 변환하는 String 확장함수 toNotiType()추가
- 기존에 NotiType을 사용하고 있는 파일들이 많아서 모두다 String으로 바꾸기에는 어려움이 있음. 또한 enum class로 상수값을 명확하게 갖고 있다면 분기처리 등 활용도가 좋기 때문에 서버 통신 시에만 잠깐 String으로 변환하기로 결정

[mod] 알림유형 데이터타입을 NotiType -> String으로 변경

---

app/src/main/java/com/hyeeyoung/wishboard/data/interceptor/AuthInterceptor.kt

릴리즈 모드에서 토큰 갱신 요청 시 새 request 생성 전에 이전 response를 close하지 않아 크래시가 발생하는 버그 수정
1. 새 request 생성 전에 이전 response를 close()하는 코드 추가

[fix] 릴리즈 모드에서 토큰 갱신 요청 시 크래시가 발생하는 버그 수정

---

app/src/main/java/com/hyeeyoung/wishboard/presentation/folder/FolderListAdapter.kt
app/src/main/java/com/hyeeyoung/wishboard/presentation/folder/FolderViewModel.kt
app/src/main/java/com/hyeeyoung/wishboard/presentation/folder/screens/FolderFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/presentation/folder/screens/FolderListBottomDialogFragment.kt
app/src/main/java/com/hyeeyoung/wishboard/util/UiState.kt
app/src/main/res/layout/fragment_folder.xml

디테일 뷰 > 폴더 선택 > 폴더 리스트가 보이지 않는 버그 수정
1. 디테일 뷰에서 폴더 선택 다이얼로그를 띄울 때 폴더 리스트가 보이지 않는 버그 수정
- 기존에 FolderViewModel에서 init { } 블록에서 호출하던 폴더 리스트 조회 함수가 지워지면서 별도로 호출했어야하는 상황인데 호출을 하지 않고 있었음
2. 폴더 추가, 조회, 수정, 삭제 관련 코드 리팩토링
- 기존에 FolderViewModel에서 FolderListAdapter 변수로 갖고 있었고, 어뎁터 내 함수들을 호출하고 있었음 -> Adatper를 Fragment 단으로 옮겨서 뷰에서 폴더 추가, 조회, 수정, 삭제 관련 Ui Update 처리를 하도록 수정

[fix] 디테일 뷰 > 폴더 선택 > 폴더 리스트가 보이지 않는 버그 수정

---

app/src/main/java/com/hyeeyoung/wishboard/presentation/common/screens/WebViewActivity.kt

- closed #428
1. 모든 액티비티와 마찬가지로 WebViewActivity도 종료 애니메이션을 보여주도록 통일
- 기존에 WebViewActivity 종료 시 애니메이션을 제거하는 코드를 제거

[del] WebViewActivity 종료 시 애니메이션을 제거하는 코드 삭제
